### ISSUE TITLE
Make keywords italic

### ISSUE THREAD

**Issue by jgierer12** [EliverLara/Andromeda#1]
I really like your theme, would you accept a PR that makes keywords italic like in https://github.com/dracula/visual-studio-code? That would make the theme much better for users of fonts with special italics styles like Operator Mono. This could also be put in a separate theme style so users can choose between normal and italic styles.

**Comment by EliverLara** [comment]
Absolutely, PR are always welcome, and I think that would be a great improvement :smiley:
