### ISSUE TITLE
Highlight active indent guide

### ISSUE THREAD

**Issue by komish** [EliverLara/Andromeda#13]
Not sure if this is a function of the theme or not, but my system's settings should always be highlighting the active indent grouping. Seems to be missing across the various versions of the theme. Is this a feature that can be added in without too much effort?

**Example:** The "hello" indent guideline is highlighted because of the cursor placement.
|Andromeda|Dark (Visual Studio)|
|---|---|
|<img width="184" alt="Screen Shot 2020-04-07 at 9 58 19 AM" src="https://user-images.githubusercontent.com/1837593/78685075-dd46b100-78b6-11ea-90ed-a714f3f9ad3b.png">|<img width="150" alt="Screen Shot 2020-04-07 at 9 58 47 AM" src="https://user-images.githubusercontent.com/1837593/78685080-de77de00-78b6-11ea-8d9c-b7bc46cca2b2.png">|

**Comment by EliverLara** [comment]
Fixed since 7158a20
