### ISSUE TITLE
Andromeda with git text colors

### ISSUE THREAD

**Issue by AbdelhakimMhioul** [EliverLara/Andromeda#28]
### Expected Behavior
The text color should be white when the file or folder is not ignored by git and grayed out when it is ignored.

### Current Behavior
The file's folders' colors are the same whether they are ignored (.gitignore) using git or not.
![image](https://user-images.githubusercontent.com/77196025/183239900-d80bec22-bfc7-4ab4-966d-e40f2f5a55c0.png)

### Possible Solution
Change the text color to white when the file or folder is not ignored by git.

### Steps to Reproduce
Just install Andromeda & enable git support for some project

**Comment by famazak** [comment]
Hey @AbdelhakimMhioul -- my new PR (#30) hopefully takes care of this

**Comment by AbdelhakimMhioul** [comment]
Yes, that solved the problem @famazak , Thanks.
