### ISSUE TITLE
Git diffs aren't highlighted properly

### ISSUE THREAD

**Issue by jgierer12** [EliverLara/Andromeda#3]
Andromeda | Dracula
--- | ---
![andromeda 5 0](https://user-images.githubusercontent.com/4331946/34737244-e2c5d474-f575-11e7-8855-e2e60de0608c.png) | ![andromeda 6 0](https://user-images.githubusercontent.com/4331946/34737245-e3ee351c-f575-11e7-9de3-6f8a9f262806.png)

**Comment by EliverLara** [comment]
Could you tell me how to get that output? I mean, colored text instead of background color, because my output is like this:

![captura de pantalla de 2018-01-09 16-34-53](https://user-images.githubusercontent.com/9838260/34747060-3aa36ca2-f55c-11e7-9a63-59e3768bdb0b.png)

**Comment by jgierer12** [comment]
Sorry for the late response, this is in diff files generated by Git, like when you do a `git commit -v`

**Comment by EliverLara** [comment]
Thanks for the info, that's fixed.

**Comment by kumarharsh** [comment]
Hi @EliverLara, in the git diff view, the comments are nearly unreadable in the green zone:

comment color:
![image](https://user-images.githubusercontent.com/760112/49853088-0dd62200-fe0c-11e8-826c-9c0444c3ebad.png)

In git diff:
![image](https://user-images.githubusercontent.com/760112/49853070-044cba00-fe0c-11e8-99a8-9ca8e764e9fb.png)
