### ISSUE TITLE
The "Comment's color" in VS Code is barely readable

### ISSUE THREAD

**Issue by AghaAmil** [EliverLara/Andromeda#31]
First all, I would like to appreciate regarding the theme you've created. I set my VS Code default theme as Andromeda.
However, I will be grateful if you brighten up or enhance the color of "Comments" code as it's somehow unreadable.
I've shared an screenshot to provide a better demonstration.

<img width="692" alt="commentFontColorIssue" src="https://user-images.githubusercontent.com/54990581/215540608-4bd9d00e-2b5b-4b4d-8ae3-671744f45fed.png">

Please let me know, if further information is required from my side.

VS Code Version: 1.74.3
Apple Macbook Pro 13 Inch (2020) - M1

**Comment by AghaAmil** [comment]
This is another example where "Comments" are not readable during a search.

![unreadableCode](https://user-images.githubusercontent.com/54990581/216663004-02e16257-bf8b-4a85-b8b0-c170eb0d5e29.png)

**Comment by EliverLara** [comment]
That was fixed with 574f85e63739e13a493f955db0385cafcb296d48
