### ISSUE TITLE
[Improvement] Theme not in Marketplate - CODE - OSS

### ISSUE THREAD

**Issue by 0hlov3** [EliverLara/Andromeda#33]
Hi there,

i'm on CODE - OSS, whem i'm searching for the Theme, i can find some Andomeda theme, but its a different one, not updated a long time.

So i'd to download the Theme Manually and install form the .vsix
https://marketplace.visualstudio.com/items?itemName=EliverLara.andromeda

Is there a way to get it working from the Marketplace?

**Comment by EliverLara** [comment]
Hi, does CODE - OSS has its own marketplace?

**Comment by 0hlov3** [comment]
Hi there,

in the https://wiki.archlinux.org/title/Visual_Studio_Code is the https://open-vsx.org mentioned, i got the normal marketplace working with the Arch Linux Documentation and everything works for me now. 

So you can close the Issue if you want.

Thanks for the reply. :)
