### ISSUE TITLE
Debug Tool Bar is off

### ISSUE THREAD

**Issue by g-kanoufi** [EliverLara/Andromeda#6]
Hi, good job with Andromeda, my new preferred theme right now :)
One thing though, the debug tool bar is off with a very wrong color.

If you want i could make a pull request but i think you'll be better doing it with a colour that fit best your theme.
The css for the debug tool bar right now(with bad colors):
```
.debug-toolbar{
    background-color: rgb(55, 47, 60);
    box-shadow: rgb(46, 51, 63) 0px 5px 8px;
}```

Hopefully you'll get the time soon to change those.

Thanks again

**Comment by EliverLara** [comment]
Hi, thanks for reporting!, I think it looks better now

| Before  | After |
| ------------- | ------------- |
| ![and1](https://user-images.githubusercontent.com/9838260/48793578-0c0db880-ecbd-11e8-87b4-975f17f9b41f.png) | ![and2](https://user-images.githubusercontent.com/9838260/48793584-12039980-ecbd-11e8-901b-08b0a52cb9a3.png) |

**Comment by g-kanoufi** [comment]
Awesome, thank you, btw is saw today that the bookmark tab on the side menu is showing all grey if you want to take a look at it too.

Thank you for fixing this so quick.
